services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    stdin_open: true
    tty: true
    network_mode: host
    command: ["./build/server/server", "--config", "./build/server/data/config.json"]

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    stdin_open: true
    tty: true
    network_mode: host

  client1:
    extends: client
    container_name: client1
    command: ["./build/client/client", "--config", "${CONFIG1}"]

  client2:
    extends: client
    container_name: client2
    command: ["./build/client/client", "--config", "${CONFIG2}"]

  client3:
    extends: client
    container_name: client3
    command: ["./build/client/client", "--config", "${CONFIG3}"]
